updated readme

diff --git a/.github/workflows/scout.yml b/.github/workflows/scout.yml
--- a/.github/workflows/scout.yml
+++ b/.github/workflows/scout.yml
@@ -20,3 +20,10 @@ jobs:
       - uses: mshick/add-pr-comment@v2.8.2
         with:
           message-path:  ${{ github.workspace }}/report.md
+
+      - name: Check for error
+        run: |
+          if [ -f "${{ github.workspace }}/FAIL" ]; then
+            echo "Error: Scout found issues."
+            exit 1
+          fi
